export interface Service {
  slug: string
  name: string
  tagline: string
  description: string
  heroImage: string
  category: string
  includes: string[]
  benefits: { title: string; description: string }[]
  process: { step: string; title: string; description: string }[]
  faqs: { question: string; answer: string }[]
  startingPrice: string
  priceNote: string
}

export const services: Service[] = [
  {
    slug: 'lawn-care-maintenance',
    name: 'Lawn Care & Maintenance',
    tagline: 'A lush, healthy lawn. Every single week.',
    description: 'From weekly mowing and edging to fertilization and weed control — we keep your lawn looking immaculate year-round so you never have to think about it.',
    heroImage: '/images/lawn-care.png',
    category: 'MAINTENANCE',
    includes: [
      'Weekly Mowing & Edging',
      'Fertilization Programs',
      'Weed & Pest Control',
      'Seasonal Overseeding',
      'Aeration Services',
      'Debris Cleanup',
    ],
    benefits: [
      { title: 'Never Miss a Week', description: "Scheduled visits on the same day every week. Rain or shine, your lawn stays perfect." },
      { title: 'Custom Fertilization', description: "We test your soil and create a fertilization plan specific to Austin's climate and your grass type." },
      { title: 'One Less Thing to Worry About', description: 'Set it and forget it. We handle everything so you can enjoy your yard, not maintain it.' },
    ],
    process: [
      { step: '01', title: 'Free Assessment', description: "We visit your property and assess your lawn's current condition, soil type, and what it needs." },
      { step: '02', title: 'Custom Plan', description: 'We build a maintenance schedule and fertilization plan tailored specifically to your lawn.' },
      { step: '03', title: 'Regular Service', description: 'Your dedicated crew shows up on the same day every week — consistent, reliable, professional.' },
      { step: '04', title: 'Ongoing Support', description: 'Spot an issue? Just call. We address problems between scheduled visits at no extra charge.' },
    ],
    faqs: [
      { question: 'How often will you visit?', answer: 'Most residential lawns are serviced weekly during the growing season (March–October) and bi-weekly in winter.' },
      { question: "Do I need to be home?", answer: "Not at all. We just need access to your yard. Most clients are at work when we visit." },
      { question: "What if it rains on my scheduled day?", answer: "We'll reschedule to the next available day and notify you by text the same morning." },
      { question: 'Do you bring your own equipment?', answer: "Yes — we bring all professional-grade equipment. You don't need to provide anything." },
    ],
    startingPrice: '$120',
    priceNote: 'per month for standard residential lots',
  },
  {
    slug: 'landscape-design',
    name: 'Landscape Design',
    tagline: 'Your vision. Expertly brought to life.',
    description: "Custom landscape designs crafted to complement your home's architecture and your personal vision for outdoor living — from concept to completion.",
    heroImage: '/images/landscapedesign.png',
    category: 'DESIGN',
    includes: [
      'Initial Consultation',
      'Digital Landscape Plans',
      'Plant Selection & Sourcing',
      'Residential & Commercial',
      '3D Visualization',
      'Phased Implementation Plans',
    ],
    benefits: [
      { title: "Designed for Austin's Climate", description: "We only specify plants and materials that thrive in Central Texas heat, drought, and soil conditions." },
      { title: 'Increases Property Value', description: 'Professional landscape design adds an average of 10–15% to home resale value.' },
      { title: 'Full-Service or Plans Only', description: 'We can design and install, or just provide the plans for you to implement yourself or with another contractor.' },
    ],
    process: [
      { step: '01', title: 'Discovery Call', description: 'We learn your style preferences, budget, how you use your outdoor space, and what you want to achieve.' },
      { step: '02', title: 'Site Assessment', description: 'We visit your property to measure, assess drainage, soil, sun exposure, and existing plants.' },
      { step: '03', title: 'Design Presentation', description: 'We present your custom digital landscape plan with plant selections, materials, and layout.' },
      { step: '04', title: 'Installation', description: 'Our crew installs your new landscape with precision, care, and minimal disruption to your daily life.' },
    ],
    faqs: [
      { question: 'How long does the design process take?', answer: 'Typically 2–3 weeks from initial consultation to final design presentation.' },
      { question: 'What does a landscape design cost?', answer: 'Design fees start at $500 for smaller projects. Full design + installation projects typically range from $5,000 to $50,000+.' },
      { question: 'Can you work with my existing plants?', answer: 'Absolutely. We assess all existing plants and incorporate the healthy ones into the new design wherever possible.' },
      { question: 'Do you handle permits?', answer: 'Yes — we handle all necessary permits for hardscaping, irrigation, and structural elements.' },
    ],
    startingPrice: '$500',
    priceNote: 'design fee · installation quoted separately',
  },
  {
    slug: 'irrigation-systems',
    name: 'Irrigation Systems',
    tagline: 'Smart watering. Lower bills. Healthier plants.',
    description: 'Smart sprinkler installation, precision repairs and seasonal optimization that saves water and money — keeping your landscape healthy without overwatering.',
    heroImage: '/images/irrigation.png',
    category: 'IRRIGATION',
    includes: [
      'Smart System Install',
      'Leak Detection & Repair',
      'Seasonal Calibration',
      'Controller Programming',
      'Zone Optimization',
      'Water Audit Reports',
    ],
    benefits: [
      { title: 'Save Up to 50% on Water Bills', description: 'Smart irrigation systems water only when needed, eliminating waste and dramatically cutting your water bill.' },
      { title: 'Healthier Plants', description: 'Consistent, precise watering produces stronger root systems and healthier plants than hand watering ever could.' },
      { title: 'Fully Automated', description: 'Set it once and forget it. Your system adjusts automatically based on weather, season, and plant needs.' },
    ],
    process: [
      { step: '01', title: 'Water Audit', description: 'We assess your current water usage, pressure, and landscape needs to design the optimal system.' },
      { step: '02', title: 'System Design', description: 'We design a zone-by-zone irrigation plan that delivers the right amount of water to every area.' },
      { step: '03', title: 'Professional Install', description: 'Our certified technicians install your system with minimal disruption to your lawn and landscaping.' },
      { step: '04', title: 'Programming & Training', description: 'We program your controller and walk you through how to use and adjust it.' },
    ],
    faqs: [
      { question: 'How long does installation take?', answer: 'Most residential installations are completed in 1–2 days depending on yard size and system complexity.' },
      { question: 'Do you service existing systems?', answer: 'Yes — we repair and optimize all makes and models of irrigation systems, not just ones we install.' },
      { question: 'What is a smart irrigation system?', answer: 'A smart system connects to local weather data and adjusts watering schedules automatically, saving significant water and money.' },
      { question: 'Do you offer seasonal startup and shutdown?', answer: 'Yes — we offer spring activation and winterization services to protect your investment year-round.' },
    ],
    startingPrice: '$1,800',
    priceNote: 'for standard residential installation',
  },
  {
    slug: 'hardscaping-patios',
    name: 'Hardscaping & Patios',
    tagline: 'Outdoor spaces built to impress.',
    description: 'Patios, walkways, retaining walls and outdoor kitchens built to last and designed to impress — turning your outdoor space into a true extension of your home.',
    heroImage: '/images/hardscaping.png',
    category: 'HARDSCAPE',
    includes: [
      'Patios & Walkways',
      'Retaining Walls',
      'Outdoor Kitchens',
      'Fire Pit Areas',
      'Pergolas & Shade Structures',
      'Decorative Concrete',
    ],
    benefits: [
      { title: 'Built to Last Decades', description: 'We use commercial-grade materials and proper base preparation — no shortcuts that lead to cracking or settling.' },
      { title: 'Adds Significant Value', description: 'A well-designed patio returns up to 80% of its cost in home value and dramatically improves quality of life.' },
      { title: 'Fully Permitted & Insured', description: 'All structural hardscaping is permitted and built to code. Your investment is protected.' },
    ],
    process: [
      { step: '01', title: 'Design Consultation', description: 'We discuss your vision, lifestyle, and budget to design the perfect outdoor living space.' },
      { step: '02', title: 'Material Selection', description: 'We help you choose from pavers, natural stone, concrete, and wood options that fit your style and budget.' },
      { step: '03', title: 'Site Preparation', description: 'Proper excavation, grading, and base preparation — the most important step that most contractors skip.' },
      { step: '04', title: 'Expert Installation', description: 'Our experienced crew installs your hardscape with precision and cleans up completely when finished.' },
    ],
    faqs: [
      { question: 'How long does a patio installation take?', answer: 'A standard patio takes 3–7 days. Larger projects with kitchens or multiple features can take 2–4 weeks.' },
      { question: 'What materials do you work with?', answer: 'Concrete pavers, natural stone (flagstone, travertine, limestone), poured concrete, brick, and composite decking.' },
      { question: 'Do you handle drainage?', answer: 'Yes — proper drainage is always incorporated into our designs to prevent water pooling and foundation issues.' },
      { question: 'What is your warranty?', answer: 'We offer a 2-year workmanship warranty on all hardscaping installations.' },
    ],
    startingPrice: '$3,500',
    priceNote: 'for standard patio installation',
  },
  {
    slug: 'seasonal-cleanup',
    name: 'Seasonal Cleanup',
    tagline: 'Spring-ready. Fall-perfect. Always.',
    description: 'Spring prep, fall leaf removal and winter readiness so your yard looks great in every season — without you lifting a finger.',
    heroImage: '/images/seasonal-cleanup.jpg',
    category: 'SEASONAL',
    includes: [
      'Spring & Fall Cleanup',
      'Leaf Removal',
      'Winter Prep',
      'Bed Edging & Mulching',
      'Debris Hauling',
      'Pruning & Trimming',
    ],
    benefits: [
      { title: 'One-Time or Recurring', description: "Book a single seasonal cleanup or set up recurring service — whatever works best for your schedule." },
      { title: 'Complete Property Coverage', description: 'We cover every inch — lawn, beds, hardscape areas, gutters, and hauling all debris away.' },
      { title: 'Same-Week Availability', description: "We keep slots open for seasonal work so you don't have to wait weeks to get on the schedule." },
    ],
    process: [
      { step: '01', title: 'Book Your Date', description: 'Schedule your cleanup online or by phone. We confirm within 24 hours and send a reminder the day before.' },
      { step: '02', title: 'Full Property Walk', description: 'Our crew walks the entire property before starting to identify everything that needs to be addressed.' },
      { step: '03', title: 'Complete Cleanup', description: 'We systematically clean every area — beds, lawn, hardscape, and gutters — leaving nothing behind.' },
      { step: '04', title: 'Debris Removal', description: 'All leaves, clippings, and debris are hauled away completely. No piles left at the curb.' },
    ],
    faqs: [
      { question: 'When should I schedule my spring cleanup?', answer: 'Ideally March–April before new growth starts. We get very busy in spring so book early.' },
      { question: 'What is included in a fall cleanup?', answer: 'Leaf removal, bed cleanup, final mowing, pruning of dead growth, and mulch application to protect roots through winter.' },
      { question: 'Do you haul everything away?', answer: 'Yes — all debris is loaded and hauled away. No bags left at the curb, no mess left behind.' },
      { question: 'Can I add mulching to my cleanup?', answer: 'Absolutely. Fresh mulch application is one of our most popular add-ons and gives beds a clean, finished look.' },
    ],
    startingPrice: '$250',
    priceNote: 'for standard residential cleanup',
  },
  {
    slug: 'garden-transformation',
    name: 'Garden Transformation',
    tagline: 'Completely reimagine your outdoor space.',
    description: 'From overgrown neglect to stunning outdoor living — our garden transformation service takes your space and creates something you will be proud of year-round.',
    heroImage: '/images/gallery7.jpg',
    category: 'DESIGN',
    includes: [
      'Full Site Clearance',
      'Hard & Soft Landscaping',
      'Turfing & Planting',
      'Feature Design',
      'Drainage Solutions',
      'Aftercare Guidance',
    ],
    benefits: [
      { title: 'One Team, Full Project', description: 'We handle everything from demolition to the final planted edge — one point of contact, zero coordination headaches.' },
      { title: 'Tailored to Your Lifestyle', description: 'Every design is built around how you want to use your outdoor space — entertaining, relaxing, or both.' },
      { title: 'Increases Property Value', description: 'A professionally transformed garden adds significant kerb appeal and increases your home\'s market value.' },
    ],
    process: [
      { step: '01', title: 'Site Visit & Brief', description: 'We walk your garden with you, listen to your ideas, and assess what the space needs.' },
      { step: '02', title: 'Design & Quote', description: 'We prepare a full design plan with clear, fixed pricing before any work begins.' },
      { step: '03', title: 'Clearance & Groundworks', description: 'Old materials are cleared, levels are set, and the structural groundwork is completed first.' },
      { step: '04', title: 'Landscaping & Finishing', description: 'Paving, turfing, planting, and features are installed to leave your garden looking exceptional.' },
    ],
    faqs: [
      { question: 'How long does a full garden transformation take?', answer: 'Most residential transformations take 1–3 weeks depending on size and complexity.' },
      { question: 'Do I need to be home during the work?', answer: 'No — we just need access to the garden. We keep you updated daily on progress.' },
      { question: 'Can you work to a strict budget?', answer: 'Yes — we design to your budget and will always present options at different price points.' },
      { question: 'Do you remove all the old materials?', answer: 'Absolutely — all debris, old paving, and garden waste is removed and disposed of responsibly.' },
    ],
    startingPrice: '£POA',
    priceNote: 'quoted based on project scope',
  },
  {
    slug: 'driveway-installation',
    name: 'Driveway Installation',
    tagline: 'Kerb appeal that lasts decades.',
    description: 'Professional driveway installations using block paving, resin bond, or porcelain — built on properly compacted sub-base foundations to prevent subsidence and cracking.',
    heroImage: '/images/gallery1.jpg',
    category: 'HARDSCAPE',
    includes: [
      'Full Site Excavation',
      'Compacted MOT Sub-Base',
      'Block, Resin & Porcelain Options',
      'Edge Restraint & Kerbing',
      'Drainage Integration',
      'Driveway Markings & Finishing',
    ],
    benefits: [
      { title: 'Built to Last 20+ Years', description: 'Proper sub-base preparation is what separates a driveway that lasts from one that cracks within 5 years.' },
      { title: 'Adds Significant Value', description: 'A smart, well-laid driveway is one of the highest-return home improvements you can make.' },
      { title: 'Fully Compliant', description: 'All our driveways meet SuDS drainage requirements and local authority regulations.' },
    ],
    process: [
      { step: '01', title: 'Site Survey', description: 'We assess your driveway area, existing surface, drainage requirements, and access constraints.' },
      { step: '02', title: 'Material Selection', description: 'We help you choose the right surface — block paving, resin, porcelain, or tarmac — for your style and budget.' },
      { step: '03', title: 'Excavation & Sub-Base', description: 'Old surface is removed, ground excavated to depth, and a compacted MOT stone sub-base is laid.' },
      { step: '04', title: 'Surface Laying & Edging', description: 'Your chosen surface is laid precisely with full edge restraints and drainage channels installed.' },
    ],
    faqs: [
      { question: 'How long does a driveway installation take?', answer: 'Most standard residential driveways are completed in 3–5 days.' },
      { question: 'Do you require planning permission?', answer: 'Most driveways don\'t require planning permission, especially with permeable surfaces. We advise on this during the survey.' },
      { question: 'Can you replace an existing driveway?', answer: 'Yes — full removal of the old surface and disposal is included in our standard process.' },
      { question: 'What is the most popular driveway surface?', answer: 'Block paving is the most popular in our area — durable, repairable, and available in a huge range of styles.' },
    ],
    startingPrice: '£2,000',
    priceNote: 'starting rate for standard residential driveways',
  },
  {
    slug: 'repaving',
    name: 'Repaving',
    tagline: 'Refresh. Restore. Reimagine.',
    description: 'Remove old, cracked, sunken, or tired paving and replace with premium natural stone, porcelain, or block paving — all laid to new-build standards.',
    heroImage: '/images/gallery5.jpg',
    category: 'HARDSCAPE',
    includes: [
      'Full Old Surface Removal',
      'Sub-Base Inspection & Repair',
      'New Stone, Porcelain or Block Laying',
      'Level & Fall Adjustment',
      'Edge Detailing & Pointing',
      'Waste Removal & Site Clean',
    ],
    benefits: [
      { title: 'Like-New Results', description: 'A proper repave doesn\'t just look better — it fixes the underlying issues that caused the old surface to fail.' },
      { title: 'Correct Drainage Falls', description: 'We reset the levels and falls correctly so water drains away from your property as it should.' },
      { title: 'Wide Material Choice', description: 'From affordable block paving to premium porcelain and natural sandstone — we work across all budgets.' },
    ],
    process: [
      { step: '01', title: 'Assessment', description: 'We inspect the existing surface and sub-base to identify what needs replacing or repairing underneath.' },
      { step: '02', title: 'Removal', description: 'All old paving is lifted and removed from site cleanly and efficiently.' },
      { step: '03', title: 'Sub-Base Repair', description: 'Any failed or weak areas underneath are repaired before the new surface goes down.' },
      { step: '04', title: 'New Surface Install', description: 'New paving is laid precisely with correct drainage falls, full pointing, and clean edge detailing.' },
    ],
    faqs: [
      { question: 'Do you always need to replace the sub-base?', answer: 'Not always — if the existing sub-base is sound we can often reuse it, which reduces cost and time.' },
      { question: 'How long does repaving take?', answer: 'A standard patio or path repave typically takes 2–4 days.' },
      { question: 'Can you match existing paving?', answer: 'We can often source matching materials, but we always show samples before ordering to ensure you\'re happy.' },
      { question: 'What causes paving to sink or crack?', answer: 'Usually a failed or inadequate sub-base, poor drainage, or tree root movement. We fix the root cause, not just the surface.' },
    ],
    startingPrice: '£750',
    priceNote: 'starting for standard path or patio repave',
  },
  {
    slug: 'grids-gravel',
    name: 'Grids & Gravel',
    tagline: 'Low maintenance. High impact.',
    description: 'Permeable gravel grid installations for driveways, paths, and parking areas — eco-friendly, drainage-compliant, and built to last without constant upkeep.',
    heroImage: '/images/gallery3.jpg',
    category: 'HARDSCAPE',
    includes: [
      'Ground Preparation & Leveling',
      'Weed Membrane Installation',
      'Plastic Grid System Laying',
      'Decorative Gravel Supply & Fill',
      'Edge Restraint Fitting',
      'Drainage Compliance Check',
    ],
    benefits: [
      { title: 'Fully Permeable', description: 'Grid systems allow rainwater to drain naturally through the surface, meeting SuDS requirements without additional drainage.' },
      { title: 'Very Low Maintenance', description: 'Once installed, gravel driveways and paths need minimal upkeep — a top-up every few years is all that\'s required.' },
      { title: 'Cost Effective', description: 'Gravel grid systems are one of the most cost-effective surfacing options available without sacrificing quality.' },
    ],
    process: [
      { step: '01', title: 'Ground Preparation', description: 'Area is excavated and leveled to the correct depth with a compacted base.' },
      { step: '02', title: 'Membrane & Grid', description: 'Weed suppression membrane is laid, followed by the plastic grid system locked into position.' },
      { step: '03', title: 'Gravel Fill', description: 'Your chosen decorative gravel is poured and spread evenly across the grid to the correct depth.' },
      { step: '04', title: 'Edging & Finish', description: 'Edge restraints are fitted and the surface is raked to a clean, level finish.' },
    ],
    faqs: [
      { question: 'Will weeds grow through a gravel grid?', answer: 'With proper membrane installation, weed growth is dramatically reduced. Occasional spot treatment may be needed over time.' },
      { question: 'Can grids support car weight?', answer: 'Yes — our grid systems are specifically rated for vehicle loads and are used for driveways across the region.' },
      { question: 'What gravel types are available?', answer: 'We offer pea gravel, crushed granite, slate chippings, and buff limestone — we can show you samples before you decide.' },
      { question: 'How long does installation take?', answer: 'Most gravel grid areas are completed in 1–2 days.' },
    ],
    startingPrice: '£500',
    priceNote: 'starting for standard areas',
  },
  {
    slug: 'block-paving',
    name: 'Block Paving',
    tagline: 'Classic finish. Structural integrity.',
    description: 'Precision block paving for driveways, patios, and paths — laid on a compacted MOT sub-base with full edging restraint systems for a finish that lasts decades.',
    heroImage: '/images/gallery5.jpg',
    category: 'HARDSCAPE',
    includes: [
      'Excavation & Sub-Base Preparation',
      'Sand Bed Laying',
      'Block Laying — Multiple Patterns',
      'Full Edge Restraint System',
      'Kiln-Dried Sand Pointing',
      'Sealing Option Available',
    ],
    benefits: [
      { title: 'Repairable for Life', description: 'Unlike concrete, individual block paving blocks can be lifted and replaced if damaged — the surface is never permanently scarred.' },
      { title: 'Huge Pattern Choice', description: 'Herringbone, stretcher bond, basketweave — we lay any pattern in a wide range of colours and finishes.' },
      { title: 'High Load Bearing', description: 'Properly laid block paving easily handles vehicle traffic and heavy loads without cracking.' },
    ],
    process: [
      { step: '01', title: 'Excavation', description: 'Area excavated to the correct depth, with all spoil removed from site.' },
      { step: '02', title: 'Sub-Base & Sand Bed', description: 'Compacted MOT sub-base is laid and blinded with a consistent sharp sand bed.' },
      { step: '03', title: 'Block Laying', description: 'Blocks are laid to your chosen pattern with consistent joint gaps and cut accurately at all edges.' },
      { step: '04', title: 'Compaction & Pointing', description: 'Surface is plate compacted and joints filled with kiln-dried sand for a solid, finished result.' },
    ],
    faqs: [
      { question: 'How long does block paving last?', answer: 'With proper installation and occasional maintenance, block paving easily lasts 30–40 years.' },
      { question: 'Do you seal block paving?', answer: 'Sealing is optional but recommended — it enhances colour, prevents weed growth, and makes cleaning easier.' },
      { question: 'Can I choose the colour and pattern?', answer: 'Absolutely — we carry a wide range of block samples and can advise on what works best for your property style.' },
      { question: 'Is block paving slippery when wet?', answer: 'Quality blocks have a textured surface specifically designed to provide grip in wet conditions.' },
    ],
    startingPrice: '£1,200',
    priceNote: 'starting for standard areas',
  },
  {
    slug: 'gazebo-installation',
    name: 'Gazebo Installation',
    tagline: 'Your outdoor retreat, built to last.',
    description: 'Bespoke timber and composite gazebo structures designed and installed to enhance your outdoor living area — giving you a sheltered, all-weather outdoor space.',
    heroImage: '/images/gallery4.jpg',
    category: 'TIMBER',
    includes: [
      'Concrete Base Preparation',
      'Timber or Composite Frame Build',
      'Roof Structure & Weatherproofing',
      'Optional Decking Floor',
      'Treated Finish & Staining',
      'Electrical Conduit Ready',
    ],
    benefits: [
      { title: 'Year-Round Outdoor Use', description: 'A well-built gazebo extends your usable outdoor season dramatically — shelter from rain and shade from summer sun.' },
      { title: 'Adds Property Value', description: 'A quality garden structure is a desirable feature that buyers consistently pay more for.' },
      { title: 'Custom Sizing', description: 'We build to your exact dimensions and garden layout — no off-the-shelf compromises.' },
    ],
    process: [
      { step: '01', title: 'Design & Sizing', description: 'We discuss your requirements and design a gazebo sized and styled to suit your garden and usage.' },
      { step: '02', title: 'Base Preparation', description: 'A solid concrete or paving base is prepared level and true before any timber work begins.' },
      { step: '03', title: 'Frame Construction', description: 'The gazebo frame is assembled on site by our experienced carpenters to exacting standards.' },
      { step: '04', title: 'Roofing & Finishing', description: 'Roof panels are fitted, timber is treated, and any additional features like decking are completed.' },
    ],
    faqs: [
      { question: 'Do I need planning permission for a gazebo?', answer: 'Most garden gazebos fall under permitted development and don\'t require planning permission. We advise on this upfront.' },
      { question: 'How long does installation take?', answer: 'A standard gazebo installation typically takes 2–4 days depending on size and base work required.' },
      { question: 'Can you add electricity to the gazebo?', answer: 'We install conduit ready for an electrician — we recommend using a qualified electrician for any electrical connections.' },
      { question: 'What timber do you use?', answer: 'We use pressure-treated structural timber that resists rot and insect damage for long-lasting results.' },
    ],
    startingPrice: '£1,800',
    priceNote: 'starting for standard gazebo structures',
  },
  {
    slug: 'shed-installation',
    name: 'Shed Installation',
    tagline: 'Practical storage. Professionally installed.',
    description: 'Supply and installation of quality timber garden sheds, concrete or slab bases, and outbuildings — built to withstand the Suffolk weather for years to come.',
    heroImage: '/images/gallery6.jpg',
    category: 'TIMBER',
    includes: [
      'Concrete or Slab Base',
      'Shed Assembly & Erection',
      'Anchoring & Weatherproofing',
      'Felt Roof Replacement Available',
      'Security Hasp & Staple Fitting',
      'Site Clear-Up',
    ],
    benefits: [
      { title: 'Properly Installed', description: 'A shed installed on a level, solid base lasts significantly longer than one sat directly on ground.' },
      { title: 'Supply & Install', description: 'We can supply the shed or install one you have already purchased — flexible to your needs.' },
      { title: 'Weatherproofed', description: 'All our sheds are treated and checked for gaps, ensuring your belongings stay dry.' },
    ],
    process: [
      { step: '01', title: 'Base Preparation', description: 'A level concrete or paving slab base is prepared to the correct size for your shed.' },
      { step: '02', title: 'Delivery & Assembly', description: 'Shed panels are assembled precisely, squared, and secured on the prepared base.' },
      { step: '03', title: 'Securing & Weatherproofing', description: 'The shed is anchored securely, roof felt checked, and any gaps sealed against the weather.' },
      { step: '04', title: 'Finishing', description: 'Doors are adjusted, ironmongery fitted, and the site is cleaned up completely.' },
    ],
    faqs: [
      { question: 'Can you install a shed I have already bought?', answer: 'Yes — we regularly install flat-pack and pre-made sheds that customers have purchased themselves.' },
      { question: 'What base do you recommend?', answer: 'A concrete base is the most durable option. For lighter sheds, a paving slab grid base works well and is easier to relocate.' },
      { question: 'Do I need planning permission for a shed?', answer: 'Most garden sheds are permitted development. Sheds over 2.5m tall or within 2m of a boundary may need permission — we advise upfront.' },
      { question: 'Can you remove an old shed first?', answer: 'Yes — we include old shed demolition and removal as part of the installation process on request.' },
    ],
    startingPrice: '£600',
    priceNote: 'starting for standard shed installations',
  },
  {
    slug: 'back-garden-makeovers',
    name: 'Back Garden Makeovers',
    tagline: 'Transform the space behind your home.',
    description: 'End-to-end back garden makeovers combining paving, turfing, planting, fencing, and structural features — all delivered by one team as a single seamless project.',
    heroImage: '/images/gallery8.jpg',
    category: 'DESIGN',
    includes: [
      'Full Design Consultation',
      'Site Clearance & Prep',
      'Paving & Pathway Installation',
      'Turfing & Planting',
      'Fencing & Boundary Features',
      'Structural Garden Features',
    ],
    benefits: [
      { title: 'Complete Transformation', description: 'We take your back garden from its current state to a finished, functional outdoor space — handled entirely by us.' },
      { title: 'Single Point of Contact', description: 'No juggling multiple trades — our team handles every element from groundworks to final planting.' },
      { title: 'Designed for Suffolk', description: 'We use materials and plants well-suited to the local climate and soil conditions for lasting results.' },
    ],
    process: [
      { step: '01', title: 'Consultation & Design', description: 'We visit, listen to your vision, and design a garden layout that works for your space and budget.' },
      { step: '02', title: 'Clearance & Groundworks', description: 'Everything unwanted is cleared, ground levels are set, and drainage is addressed from the start.' },
      { step: '03', title: 'Hard Landscaping', description: 'Paving, paths, edging, fencing, and structural features are installed first.' },
      { step: '04', title: 'Soft Landscaping & Finishing', description: 'Turf, plants, and finishing touches are applied to bring the garden to life.' },
    ],
    faqs: [
      { question: 'How long does a full back garden makeover take?', answer: 'Most projects take 1–3 weeks. Larger or more complex gardens may take longer — we always give a clear timeline upfront.' },
      { question: 'Can I choose which elements to include?', answer: 'Absolutely — we build your makeover around your priorities and budget. You choose what goes in.' },
      { question: 'Do you work in smaller back gardens?', answer: 'Yes — we work in all sizes of garden, from compact terraced plots to larger detached properties.' },
      { question: 'What if the garden is very overgrown?', answer: 'No problem — full clearance of overgrown vegetation, old structures, and waste is part of our standard process.' },
    ],
    startingPrice: '£POA',
    priceNote: 'quoted based on project scope',
  },
]

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find(s => s.slug === slug)
}

export function getAllServiceSlugs(): string[] {
  return services.map(s => s.slug)
}
